# Generated by Django 3.2.4 on 2021-10-06 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(choices=[('DELUXE', 'DELUXE'), ('GUEST', 'GUEST'), ('LUXURY', 'LUXURY'), ('SINGLE', 'SINGLE')], max_length=10)),
            ],
            options={
                'verbose_name_plural': ' Room Category',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('available', 'available'), ('unavailable', 'unavailable'), ('comfirmed', 'confirmed')], max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Room Status',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.IntegerField()),
                ('room_number', models.CharField(choices=[('001', '001'), ('002', '002'), ('003', '003'), ('004', '004'), ('005', '005'), ('006', '006'), ('007', '007'), ('008', '008'), ('009', '009'), ('010', '010'), ('011', '011'), ('012', '012'), ('013', '013'), ('014', '014'), ('015', '015'), ('016', '016'), ('017', '017'), ('018', '018'), ('019', '019'), ('020', '020')], max_length=15)),
                ('description', models.TextField()),
                ('reference_code', models.IntegerField()),
                ('price', models.IntegerField()),
                ('room_category', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='second_hotel.category')),
                ('status', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='second_hotel.status')),
            ],
            options={
                'verbose_name_plural': 'Rooms',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=20, null=True)),
                ('message', models.TextField()),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customerrs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('phone_no', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=20, null=True)),
                ('address', models.CharField(max_length=20, null=True)),
                ('nationality', models.CharField(max_length=20, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('customerrs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='second_hotel.customerrs')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='second_hotel.room')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Room Booking',
            },
        ),
    ]
