# Generated by Django 3.2.4 on 2021-10-06 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second_hotel', '0003_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='email',
        ),
        migrations.RemoveField(
            model_name='message',
            name='name',
        ),
    ]
