# Generated by Django 3.2.4 on 2021-10-06 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second_hotel', '0006_alter_message_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
    ]
