# Generated by Django 3.2.4 on 2021-10-10 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('second_hotel', '0012_alter_booking_customerrs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='customerrs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='second_hotel.customerrs'),
        ),
    ]
