# Generated by Django 3.2.4 on 2021-10-10 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second_hotel', '0013_alter_booking_customerrs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
    ]
