# Generated by Django 3.2.4 on 2021-10-17 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second_hotel', '0018_auto_20211017_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerrs',
            name='is_updated',
        ),
    ]
