# Generated by Django 3.2.4 on 2021-10-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_hotel', '0019_remove_customerrs_is_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrs',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
