# Generated by Django 3.2.4 on 2021-10-18 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second_hotel', '0020_customerrs_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerrs',
            name='is_verified',
        ),
    ]
