# Generated by Django 3.2.4 on 2021-11-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_hotel', '0021_remove_customerrs_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerrs',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customerrs',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customerrs',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customerrs',
            name='nationality',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customerrs',
            name='phone_no',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
