# Generated by Django 3.2.4 on 2021-11-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_hotel', '0022_auto_20211101_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerrs',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
