# Generated by Django 3.2.4 on 2021-11-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_hotel', '0023_alter_customerrs_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerrs',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
