# Generated by Django 3.2.4 on 2021-11-06 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_hotel', '0024_alter_customerrs_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrs',
            name='is_verfied',
            field=models.BooleanField(default=False),
        ),
    ]
